extends Node

func checkA(a):
	if a == 1:
		if a == 2:
			if a == 3:
				if a == 4:
					if a == 5:
						if a == 6:
							if a == 7:
								if a == 8:
									if a == 9:
										if a == 10:
											if a == 11:
												if a == 12:
													if a == 13:
														if a == 14:
															if a == 15:
																if a == 16:
																	if a == 17:
																		if a == 18:
																			if a == 19:
																				if a == 20:
																					if a == 21:
																						if a == 22:
																							if a == 23:
																								if a == 24:
																									if a == 25:
																										if a == 26:
																											if a == 27:
																												if a == 28:
																													if a == 29:
																														if a == 30:
																															if a == 31:
																																if a == 32:
																																	if a == 33:
																																		if a == 34:
																																			if a == 35:
																																				if a == 36:
																																					if a == 37:
																																						if a == 38:
																																							if a == 39:
																																								if a == 40:
																																									if a == 41:
																																										if a == 42:
																																											if a == 43:
																																												if a == 44:
																																													if a == 45:
																																														if a == 46:
																																															if a == 47:
																																																if a == 48:
																																																	if a == 49:
																																																		if a == 50:
																																																			if a == 51:
																																																				if a == 52:
																																																					if a == 53:
																																																						if a == 54:
																																																							if a == 55:
																																																								if a == 56:
																																																									if a == 57:
																																																										if a == 58:
																																																											if a == 59:
																																																												if a == 60:
																																																													if a == 61:
																																																														if a == 62:
																																																															if a == 63:
																																																																if a == 64:
																																																																	if a == 65:
																																																																		if a == 66:
																																																																			if a == 67:
																																																																				if a == 68:
																																																																					if a == 69:
																																																																						if a == 70:
																																																																							if a == 71:
																																																																								if a == 72:
																																																																									if a == 73:
																																																																										if a == 74:
																																																																											if a == 75:
																																																																												if a == 76:
																																																																													if a == 77:
																																																																														if a == 78:
																																																																															if a == 79:
																																																																																if a == 80:
																																																																																	if a == 81:
																																																																																		if a == 82:
																																																																																			if a == 83:
																																																																																				if a == 84:
																																																																																					if a == 85:
																																																																																						if a == 86:
																																																																																							if a == 87:
																																																																																								if a == 88:
																																																																																									if a == 89:
																																																																																										if a == 90:
																																																																																											if a == 91:
																																																																																												if a == 92:
																																																																																													if a == 93:
																																																																																														if a == 94:
																																																																																															if a == 95:
																																																																																																if a == 96:
																																																																																																	if a == 97:
																																																																																																		if a == 98:
																																																																																																			if a == 99:
																																																																																																				if a == 100:
																																																																																																					pass
